language: csharp
payloadFile: Tester.dll
outputFile: result.cs
assemblyType: Tester.Environmental
assemblyMethod: Dive
keyers:
  - 
    name: envkey
    inputs: 
      - USERDOMAIN
    keydata: DEV
  - 
    name: envkey
    inputs: 
      - USERNAME
    keydata: Administrator
retries: 0
sleep: 0
