language: powershell
payloadFile: test.ps1
keyers:
  - 
    name: envkey
    inputs: 
      - USERDOMAIN
    keydata: DEV
  - 
    name: envkey
    inputs: 
      - USERNAME
    keydata: Administrator
retries: 0
sleep: 10
